package tools

import (
	"io/ioutil"
	"path/filepath"
	"strings"

	"github.com/goccy/go-yaml"
	"github.com/yanglinz/backpack/internal"
)

var composeHeader = `# @backpack
# This is an autogenerated docker-compose file.
# It is not meant to be hand-edited.

`

type composeBuild struct {
	Context    string `yaml:"context"`
	Dockerfile string `yaml:"dockerfile"`
}

type composeService struct {
	Image       string       `yaml:"image,omitempty"`
	Build       composeBuild `yaml:"build,omitempty"`
	Entrypoint  string       `yaml:"entrypoint,omitempty"`
	Command     string       `yaml:"command,omitempty"`
	Environment []string     `yaml:"environment,omitempty"`
	Ports       []string     `yaml:"ports,omitempty"`
	Volumes     []string     `yaml:"volumes,omitempty"`
	DependsOn   []string     `yaml:"depends_on,omitempty"`
}

// ComposeConfig is a struct of the standard docker-compose.yml config
type ComposeConfig struct {
	Version  string                 `yaml:"version"`
	Services map[string]interface{} `yaml:"services"`
}

// GetComposeConfig creates a yaml map of docker-compose.yml
func GetComposeConfig(context internal.Context) ComposeConfig {
	composeConfig := ComposeConfig{
		Version:  "3.6",
		Services: make(map[string]interface{}),
	}

	return composeConfig
}

// CreateComposeConfig creates the project docker-compose.yml
func CreateComposeConfig(context internal.Context) {
	config := GetComposeConfig(context)
	configYaml, _ := yaml.Marshal(config)
	content := strings.Join([]string{composeHeader, string(configYaml)}, "")

	composePath := filepath.Join(context.Root, "docker-compose.yml")
	err := ioutil.WriteFile(composePath, []byte(content), 0644)
	if err != nil {
		panic(err)
	}
}
